# Generated by Django 2.1.4 on 2018-12-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181230_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='reditiavatar.png', upload_to=''),
        ),
    ]
