# Generated by Django 2.1.4 on 2018-12-30 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0002_auto_20181230_0322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-created']},
        ),
    ]
