# Generated by Django 2.1.4 on 2019-01-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0005_auto_20190108_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
